<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_comment_commentvote' => [['id', 'direction'], ['_controller' => 'App\\Controller\\CommentController::commentVote'], ['direction' => 'up|down'], [['variable', '/', 'up|down', 'direction', true], ['text', '/vote'], ['variable', '/', '[^/]++', 'id', true], ['text', '/comments']], [], []],
    'app_homepage' => [[], ['_controller' => 'App\\Controller\\QuestionController::homepage'], [], [['text', '/']], [], []],
    'app_question_show' => [['slug'], ['_controller' => 'App\\Controller\\QuestionController::show'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/questions']], [], []],
];
