<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3WpJw73\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3WpJw73/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3WpJw73.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3WpJw73\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3WpJw73\App_KernelDevDebugContainer([
    'container.build_hash' => '3WpJw73',
    'container.build_id' => 'e3190304',
    'container.build_time' => 1681601302,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3WpJw73');
